# Generated by Django 5.0.1 on 2025-10-13 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Metric name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Metric description')),
                ('metric_type', models.CharField(choices=[('goal_completion', 'Goal Completion Rate'), ('review_completion', 'Review Completion Rate'), ('feedback_response', 'Feedback Response Rate'), ('performance_rating', 'Average Performance Rating'), ('goal_achievement', 'Goal Achievement Score'), ('custom', 'Custom Metric')], help_text='Type of metric', max_length=30)),
                ('calculation_method', models.TextField(help_text='How the metric is calculated')),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the metric is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dashboard name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Dashboard description')),
                ('is_public', models.BooleanField(default=False, help_text='Whether the dashboard is public')),
                ('configuration', models.JSONField(default=dict, help_text='Dashboard configuration and layout')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the dashboard is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Dashboard owner', on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Report name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Report description')),
                ('report_type', models.CharField(choices=[('performance', 'Performance Report'), ('goals', 'Goals Report'), ('feedback', 'Feedback Report'), ('reviews', 'Reviews Report'), ('analytics', 'Analytics Report'), ('custom', 'Custom Report')], help_text='Type of report', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the report', max_length=20)),
                ('parameters', models.JSONField(default=dict, help_text='Report parameters and filters')),
                ('file_path', models.CharField(blank=True, help_text='Path to the generated report file', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size of the report file in bytes', null=True)),
                ('generated_at', models.DateTimeField(blank=True, help_text='When the report was generated', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the report expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this report', on_delete=django.db.models.deletion.CASCADE, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
