# Generated by Django 5.0.1 on 2025-10-13 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('goal_creation', 'Goal Creation'), ('goal_approval', 'Goal Approval'), ('goal_progress', 'Goal Progress Tracking'), ('peer_feedback_request', 'Peer Feedback Request'), ('peer_feedback_submission', 'Peer Feedback Submission'), ('self_review', 'Self Review'), ('manager_review', 'Manager Review'), ('calibration', 'Calibration'), ('final_review', 'Final Review')], help_text='Type of workflow step', max_length=50)),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr', 'HR Administrator'), ('admin', 'Admin')], help_text='Role for this workflow step', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('overdue', 'Overdue')], default='not_started', help_text='Current status of the workflow step', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this step in the workflow')),
                ('started_at', models.DateTimeField(blank=True, help_text='When this step was started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this step was completed', null=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='Due date for this step', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this workflow step')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(help_text='Review cycle for this workflow step', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='cycles.reviewcycle')),
                ('user', models.ForeignKey(help_text='User for this workflow step', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Step',
                'verbose_name_plural': 'Workflow Steps',
                'ordering': ['cycle', 'role', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reminder', 'Reminder'), ('deadline_alert', 'Deadline Alert'), ('overdue_alert', 'Overdue Alert'), ('completion', 'Completion Notification'), ('approval_request', 'Approval Request'), ('approval_response', 'Approval Response')], help_text='Type of notification', max_length=30)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was sent')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('user', models.ForeignKey(help_text='User to notify', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to=settings.AUTH_USER_MODEL)),
                ('workflow_step', models.ForeignKey(blank=True, help_text='Related workflow step', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflows.workflowstep')),
            ],
            options={
                'verbose_name': 'Workflow Notification',
                'verbose_name_plural': 'Workflow Notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('approve', 'Approve'), ('reject', 'Reject'), ('submit', 'Submit'), ('export', 'Export')], help_text='Type of action performed', max_length=20)),
                ('model_name', models.CharField(help_text='Name of the model affected', max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the object affected', null=True)),
                ('changes', models.JSONField(blank=True, help_text='JSON representation of changes made', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='workflows_a_user_id_e3716d_idx'), models.Index(fields=['model_name', 'object_id'], name='workflows_a_model_n_d34897_idx'), models.Index(fields=['-timestamp'], name='workflows_a_timesta_a48626_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workflowstep',
            index=models.Index(fields=['user', 'cycle', 'status'], name='workflows_w_user_id_dce51c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstep',
            index=models.Index(fields=['cycle', 'role', 'status'], name='workflows_w_cycle_i_666372_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('user', 'cycle', 'step_type')},
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['user', 'is_read'], name='workflows_w_user_id_e2bb40_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownotification',
            index=models.Index(fields=['-sent_at'], name='workflows_w_sent_at_8c2deb_idx'),
        ),
    ]
