# Generated by Django 5.0.1 on 2025-10-13 13:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('code', models.CharField(help_text='Department code (e.g., HR, IT, SALES)', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True, help_text='Department description')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Department budget', max_digits=15, null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location of the department', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the department is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, help_text='Department manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
                ('parent_department', models.ForeignKey(blank=True, help_text='Parent department in the hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='org.department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Team description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the team is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Department this team belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='org.department')),
                ('team_lead', models.ForeignKey(blank=True, help_text='Team lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='member', help_text='Role in the team', max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the membership is active')),
                ('team', models.ForeignKey(help_text='Team', on_delete=django.db.models.deletion.CASCADE, to='org.team')),
                ('user', models.ForeignKey(help_text='Team member', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Membership',
                'verbose_name_plural': 'Team Memberships',
                'unique_together': {('user', 'team')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(help_text='Team members', related_name='teams', through='org.TeamMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=100)),
                ('description', models.TextField(help_text='Job description')),
                ('requirements', models.TextField(blank=True, help_text='Job requirements')),
                ('responsibilities', models.TextField(blank=True, help_text='Job responsibilities')),
                ('level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director'), ('executive', 'Executive')], default='mid', help_text='Position level', max_length=20)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary for this position', max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary for this position', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the position is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Department this position belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='org.department')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['title'],
                'unique_together': {('title', 'department')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'department')},
        ),
    ]
