# Generated by Django 5.0.1 on 2025-10-13 13:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('color', models.CharField(default='#007bff', help_text='Color code for the category (hex)', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the category is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Goal Category',
                'verbose_name_plural': 'Goal Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Goal title', max_length=200)),
                ('description', models.TextField(help_text='Detailed goal description')),
                ('specific', models.TextField(help_text='Specific: What exactly will be accomplished?')),
                ('measurable', models.TextField(help_text='Measurable: How will success be measured?')),
                ('achievable', models.TextField(help_text='Achievable: Is this goal realistic and attainable?')),
                ('relevant', models.TextField(help_text='Relevant: How does this align with broader objectives?')),
                ('time_bound', models.TextField(help_text='Time-bound: What is the deadline and timeline?')),
                ('goal_type', models.CharField(choices=[('performance', 'Performance'), ('development', 'Development'), ('behavioral', 'Behavioral'), ('project', 'Project'), ('stretch', 'Stretch')], default='performance', help_text='Type of goal', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Goal priority level', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='draft', help_text='Current status of the goal', max_length=20)),
                ('metric', models.CharField(help_text='Primary metric for measuring success', max_length=100)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, help_text='Target value for the metric', max_digits=10, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current value of the metric', max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (e.g., %, $, hours)', max_length=50)),
                ('start_date', models.DateField(help_text='Goal start date')),
                ('target_date', models.DateField(help_text='Goal target completion date')),
                ('completed_date', models.DateField(blank=True, help_text='Actual completion date', null=True)),
                ('weight', models.PositiveIntegerField(default=10, help_text='Weight of this goal in overall evaluation (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the goal was approved', null=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Current progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time the goal was updated')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the goal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager who approved this goal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_goals', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(help_text='Review cycle this goal belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='cycles.reviewcycle')),
                ('employee', models.ForeignKey(help_text='Employee who owns this goal', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.PositiveIntegerField(help_text='Progress percentage at the time of update', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current value of the metric', max_digits=10, null=True)),
                ('comments', models.TextField(help_text='Comments about the progress update')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(help_text='Goal being updated', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='goals.goal')),
                ('updated_by', models.ForeignKey(help_text='User who made the update', on_delete=django.db.models.deletion.CASCADE, related_name='goal_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goal Update',
                'verbose_name_plural': 'Goal Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
