# Generated by Django 5.0.1 on 2025-10-13 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Objective name', max_length=200)),
                ('description', models.TextField(help_text='Objective description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Objective priority level', max_length=10)),
                ('target_date', models.DateField(help_text='Target completion date')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_track', 'On Track'), ('at_risk', 'At Risk'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', help_text='Current status of the objective', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the objective is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department this objective belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='org.department')),
                ('owner', models.ForeignKey(help_text='Executive owner of this objective', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_objectives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Objective',
                'verbose_name_plural': 'Business Objectives',
                'ordering': ['-priority', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='GoalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(help_text='Template description')),
                ('goal_type', models.CharField(choices=[('performance', 'Performance'), ('development', 'Development'), ('behavioral', 'Behavioral'), ('project', 'Project'), ('stretch', 'Stretch')], help_text='Type of goal this template is for', max_length=20)),
                ('specific_template', models.TextField(help_text='Template for specific criteria with placeholders')),
                ('measurable_template', models.TextField(help_text='Template for measurable criteria with placeholders')),
                ('achievable_template', models.TextField(help_text='Template for achievable criteria with placeholders')),
                ('relevant_template', models.TextField(help_text='Template for relevant criteria with placeholders')),
                ('time_bound_template', models.TextField(help_text='Template for time-bound criteria with placeholders')),
                ('guidance', models.TextField(blank=True, help_text='Guidance for using this template')),
                ('example', models.TextField(blank=True, help_text='Example goal using this template')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the template is active')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this template has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category this template belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='goals.goalcategory')),
                ('created_by', models.ForeignKey(help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goal_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goal Template',
                'verbose_name_plural': 'Goal Templates',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GoalAlignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment_strength', models.CharField(choices=[('weak', 'Weak'), ('moderate', 'Moderate'), ('strong', 'Strong'), ('critical', 'Critical')], default='moderate', help_text='Strength of alignment', max_length=20)),
                ('justification', models.TextField(blank=True, help_text='Justification for how this goal aligns to the objective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(help_text='Goal being aligned', on_delete=django.db.models.deletion.CASCADE, related_name='alignments', to='goals.goal')),
                ('objective', models.ForeignKey(help_text='Business objective this goal aligns to', on_delete=django.db.models.deletion.CASCADE, related_name='aligned_goals', to='goals.businessobjective')),
            ],
            options={
                'verbose_name': 'Goal Alignment',
                'verbose_name_plural': 'Goal Alignments',
                'unique_together': {('goal', 'objective')},
            },
        ),
        migrations.CreateModel(
            name='GoalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Version number')),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('progress_updated', 'Progress Updated'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], help_text='Type of change made', max_length=20)),
                ('data_snapshot', models.JSONField(help_text='JSON snapshot of goal data at this version')),
                ('change_summary', models.TextField(blank=True, help_text='Summary of changes made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_version_changes', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(help_text='Goal this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='goals.goal')),
            ],
            options={
                'verbose_name': 'Goal Version',
                'verbose_name_plural': 'Goal Versions',
                'ordering': ['-created_at'],
                'unique_together': {('goal', 'version_number')},
            },
        ),
    ]
