# Generated by Django 5.0.1 on 2025-10-13 20:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_businessobjective_goaltemplate_goalalignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='draft', help_text='Current status of the goal', max_length=20),
        ),
        migrations.CreateModel(
            name='GoalFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('approval', 'Approval'), ('request_changes', 'Request Changes'), ('rejection', 'Rejection'), ('suggestion', 'Suggestion'), ('alignment_comment', 'Alignment Comment')], help_text='Type of feedback being provided', max_length=20)),
                ('comments', models.TextField(help_text='Manager feedback comments')),
                ('smart_specific', models.BooleanField(default=True, help_text='Goal clearly defines what will be accomplished')),
                ('smart_measurable', models.BooleanField(default=True, help_text='Quantifiable success metrics are present')),
                ('smart_achievable', models.BooleanField(default=True, help_text='Goal is realistic given resources and timeframe')),
                ('smart_relevant', models.BooleanField(default=True, help_text='Aligns with business objectives and role responsibilities')),
                ('smart_time_bound', models.BooleanField(default=True, help_text='Clear deadline within review cycle')),
                ('alignment_score', models.PositiveIntegerField(blank=True, help_text='Business alignment rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('challenge_level', models.CharField(blank=True, choices=[('too_easy', 'Too Easy'), ('appropriate', 'Appropriate'), ('too_ambitious', 'Too Ambitious')], help_text='Manager assessment of goal difficulty', max_length=20, null=True)),
                ('suggested_modifications', models.TextField(blank=True, help_text='Specific suggestions for goal improvement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(help_text='Goal being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='goals.goal')),
                ('manager', models.ForeignKey(help_text='Manager providing feedback', on_delete=django.db.models.deletion.CASCADE, related_name='goal_feedback_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goal Feedback',
                'verbose_name_plural': 'Goal Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
