# Generated by Django 5.0.1 on 2025-10-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goal_status_goalfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='achievable',
            field=models.TextField(blank=True, default='', help_text='Achievable: Is this goal realistic and attainable?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='measurable',
            field=models.TextField(blank=True, default='', help_text='Measurable: How will success be measured?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='relevant',
            field=models.TextField(blank=True, default='', help_text='Relevant: How does this align with broader objectives?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='specific',
            field=models.TextField(blank=True, default='', help_text='Specific: What exactly will be accomplished?'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='time_bound',
            field=models.TextField(blank=True, default='', help_text='Time-bound: What is the deadline and timeline?'),
        ),
    ]
