# Generated by Django 5.0.1 on 2025-10-13 13:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('questions', models.JSONField(help_text='List of questions in the template')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the template is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feedback Template',
                'verbose_name_plural': 'Feedback Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', help_text='Current status of the feedback request', max_length=20)),
                ('message', models.TextField(help_text='Message from the requester')),
                ('due_date', models.DateTimeField(help_text='Due date for the feedback')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the feedback was submitted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(help_text='Review cycle this feedback belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to='cycles.reviewcycle')),
                ('recipient', models.ForeignKey(help_text='Employee being asked for feedback', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(help_text='Employee requesting feedback', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Request',
                'verbose_name_plural': 'Feedback Requests',
                'ordering': ['-created_at'],
                'unique_together': {('requester', 'recipient', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveIntegerField(help_text='Overall rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('strengths', models.TextField(help_text='Strengths and positive aspects')),
                ('areas_for_improvement', models.TextField(help_text='Areas for improvement')),
                ('specific_examples', models.TextField(help_text='Specific examples and observations')),
                ('recommendations', models.TextField(help_text='Recommendations for development')),
                ('additional_comments', models.TextField(blank=True, help_text='Any additional comments')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Whether the feedback is anonymous')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(help_text='Feedback request being responded to', on_delete=django.db.models.deletion.CASCADE, related_name='response', to='feedback.feedbackrequest')),
            ],
            options={
                'verbose_name': 'Feedback Response',
                'verbose_name_plural': 'Feedback Responses',
                'ordering': ['-created_at'],
            },
        ),
    ]
