# Generated by Django 5.0.1 on 2025-10-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='When the last reminder was sent', null=True),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='manager_notified',
            field=models.BooleanField(default=False, help_text='Whether manager has been notified of non-response (BR-024)'),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='manager_notified_at',
            field=models.DateTimeField(blank=True, help_text='When manager was notified', null=True),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='relationship_description',
            field=models.TextField(blank=True, help_text='Optional description of working relationship'),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='relationship_type',
            field=models.CharField(choices=[('direct_report', 'Direct Report'), ('peer_same_team', 'Peer - Same Team'), ('peer_other_team', 'Peer - Other Team'), ('cross_functional', 'Cross-Functional Collaborator'), ('project_team', 'Project Team Member'), ('mentor_mentee', 'Mentor/Mentee'), ('other', 'Other')], default='peer_other_team', help_text='Working relationship context', max_length=30),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of reminders sent'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='competency_ratings',
            field=models.JSONField(default=dict, help_text='Ratings for behavioral competencies'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='content_policy_passed',
            field=models.BooleanField(default=False, help_text='Whether content passed policy validation (BR-023)'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='Whether this is a draft (allows partial save)'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='validation_issues',
            field=models.JSONField(blank=True, default=dict, help_text='Content policy validation issues detected'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='due_date',
            field=models.DateTimeField(help_text='Due date for the feedback (BR-025)'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='message',
            field=models.TextField(help_text='Personalized message from the requester'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='areas_for_improvement',
            field=models.TextField(help_text='Areas for improvement (min 20 words)'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Whether the feedback is anonymous (BR-026)'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='specific_examples',
            field=models.TextField(help_text='Specific examples of collaboration (min 15 words)'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='strengths',
            field=models.TextField(help_text='Strengths and positive aspects (min 20 words)'),
        ),
    ]
