# Generated by Django 5.0.1 on 2025-10-18 08:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_competency_ratingscale_cycleratingscale_and_more'),
        ('feedback', '0003_managerfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacktemplate',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Feedback Template', 'verbose_name_plural': 'Feedback Templates'},
        ),
        migrations.AlterUniqueTogether(
            name='feedbackrequest',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='areas_for_improvement',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='competency_ratings',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='content_policy_passed',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='request',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='specific_examples',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='validation_issues',
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='allow_anonymous',
            field=models.BooleanField(default=True, help_text='Whether anonymous feedback is allowed'),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Deadline for feedback submission'),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description'),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='max_peers',
            field=models.IntegerField(default=5, help_text='Maximum number of peer reviewers allowed', validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='min_peers',
            field=models.IntegerField(default=1, help_text='Minimum number of peer reviewers required', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='title',
            field=models.CharField(default='Feedback Request', help_text='Title for this feedback request', max_length=200),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='adaptability_rating',
            field=models.IntegerField(blank=True, help_text='Adaptability rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='collaboration_examples',
            field=models.TextField(blank=True, help_text='Specific examples of working together'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='collaboration_rating',
            field=models.IntegerField(blank=True, help_text='Collaboration skills rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='communication_rating',
            field=models.IntegerField(blank=True, help_text='Communication skills rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='content_policy_approved',
            field=models.BooleanField(default=False, help_text='Whether content policy review is approved'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='content_policy_violations',
            field=models.JSONField(blank=True, default=list, help_text='List of content policy violations found'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='development_areas',
            field=models.TextField(blank=True, help_text='Areas for development and improvement'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='is_submitted',
            field=models.BooleanField(default=False, help_text='Whether the response has been submitted'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='leadership_rating',
            field=models.IntegerField(blank=True, help_text='Leadership skills rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='problem_solving_rating',
            field=models.IntegerField(blank=True, help_text='Problem-solving skills rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktemplate',
            name='competencies',
            field=models.JSONField(default=list, help_text='List of competencies to evaluate'),
        ),
        migrations.AddField(
            model_name='feedbacktemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbacktemplate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this is the default template'),
        ),
        migrations.AddField(
            model_name='feedbacktemplate',
            name='rating_scale',
            field=models.JSONField(default=dict, help_text='Rating scale configuration'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='cycle',
            field=models.ForeignKey(help_text='Performance cycle for this feedback', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to='cycles.reviewcycle'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the feedback request', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='additional_comments',
            field=models.TextField(blank=True, help_text='Additional comments or observations'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Whether the reviewer chose to remain anonymous'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='overall_rating',
            field=models.IntegerField(blank=True, help_text='Overall performance rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='strengths',
            field=models.TextField(blank=True, help_text='Strengths and positive contributions'),
        ),
        migrations.AlterField(
            model_name='feedbacktemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feedbacktemplate',
            name='name',
            field=models.CharField(help_text='Template name', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedbacktemplate',
            name='questions',
            field=models.JSONField(default=list, help_text='Standardized questions for feedback'),
        ),
        migrations.CreateModel(
            name='ContentPolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the policy rule', max_length=100)),
                ('rule_type', models.CharField(choices=[('profanity', 'Profanity Filter'), ('bias', 'Bias Detection'), ('tone', 'Tone Analysis'), ('length', 'Length Requirements'), ('professional', 'Professional Language')], help_text='Type of content policy rule', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Severity level of violations', max_length=10)),
                ('keywords', models.JSONField(default=list, help_text='Keywords or phrases to flag')),
                ('patterns', models.JSONField(default=list, help_text='Regex patterns for detection')),
                ('min_length', models.IntegerField(blank=True, help_text='Minimum length requirement', null=True)),
                ('max_length', models.IntegerField(blank=True, help_text='Maximum length limit', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_block', models.BooleanField(default=False, help_text='Whether to automatically block submission')),
                ('warning_message', models.TextField(help_text='Message to show when rule is violated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_policy_rules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Policy Rule',
                'verbose_name_plural': 'Content Policy Rules',
                'ordering': ['severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PeerReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_context', models.TextField(blank=True, help_text='Context about the working relationship')),
                ('personal_message', models.TextField(blank=True, help_text='Personal message from requester to reviewer')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', help_text='Status of this peer review', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_count', models.IntegerField(default=0)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('feedback_request', models.ForeignKey(help_text='The feedback request this reviewer is part of', on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviewers', to='feedback.feedbackrequest')),
                ('reviewer', models.ForeignKey(help_text='The peer reviewer', on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Peer Reviewer',
                'verbose_name_plural': 'Peer Reviewers',
                'ordering': ['invited_at'],
                'unique_together': {('feedback_request', 'reviewer')},
            },
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='peer_reviewer',
            field=models.OneToOneField(blank=True, help_text='The peer reviewer who submitted this response', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='feedback.peerreviewer'),
        ),
        migrations.DeleteModel(
            name='ManagerFeedback',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='last_reminder_sent',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='manager_notified',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='manager_notified_at',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='message',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='relationship_description',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='relationship_type',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='reminder_count',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='submitted_at',
        ),
    ]
