# Generated by Django 5.0.1 on 2025-10-18 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_competency_ratingscale_cycleratingscale_and_more'),
        ('feedback', '0004_alter_feedbacktemplate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('recognition', 'Recognition'), ('constructive', 'Constructive'), ('coaching', 'Coaching'), ('development', 'Development'), ('general', 'General')], default='general', help_text='Type of feedback', max_length=20)),
                ('subject', models.CharField(help_text='Brief subject/title of the feedback', max_length=200)),
                ('feedback', models.TextField(help_text='Detailed feedback content')),
                ('strengths', models.TextField(blank=True, help_text='Specific strengths observed (optional)')),
                ('areas_for_improvement', models.TextField(blank=True, help_text='Areas for growth and development (optional)')),
                ('action_items', models.TextField(blank=True, help_text='Suggested action items or next steps (optional)')),
                ('visibility', models.CharField(choices=[('private', 'Private (Manager & Employee only)'), ('hr', 'Visible to HR'), ('public', 'Public (Visible to all)')], default='private', help_text='Who can view this feedback', max_length=20)),
                ('is_acknowledged', models.BooleanField(default=False, help_text='Whether employee has acknowledged viewing this feedback')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When employee acknowledged the feedback', null=True)),
                ('employee_response', models.TextField(blank=True, help_text='Optional response from the employee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(blank=True, help_text='Optional: Associated review cycle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_feedback', to='cycles.reviewcycle')),
                ('employee', models.ForeignKey(help_text='Employee receiving the feedback', on_delete=django.db.models.deletion.CASCADE, related_name='manager_feedback_received', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(help_text='Manager providing the feedback', on_delete=django.db.models.deletion.CASCADE, related_name='manager_feedback_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manager Feedback',
                'verbose_name_plural': 'Manager Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['manager', 'employee'], name='feedback_ma_manager_3811c3_idx'), models.Index(fields=['employee', '-created_at'], name='feedback_ma_employe_3bd0a6_idx'), models.Index(fields=['-created_at'], name='feedback_ma_created_a6b021_idx')],
            },
        ),
    ]
