# Generated by Django 5.0.1 on 2025-10-13 13:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('cycle_type', models.CharField(choices=[('annual', 'Annual'), ('mid_year', 'Mid-Year'), ('quarterly', 'Quarterly'), ('probation', 'Probation'), ('project', 'Project-Based')], help_text='Type of review cycle', max_length=20)),
                ('default_duration_days', models.PositiveIntegerField(default=365, help_text='Default duration in days')),
                ('goal_setting_days', models.PositiveIntegerField(default=30, help_text='Goal setting period in days')),
                ('self_review_days', models.PositiveIntegerField(default=14, help_text='Self-review period in days')),
                ('manager_review_days', models.PositiveIntegerField(default=14, help_text='Manager review period in days')),
                ('calibration_days', models.PositiveIntegerField(blank=True, help_text='Calibration period in days', null=True)),
                ('requires_goals', models.BooleanField(default=True)),
                ('requires_self_review', models.BooleanField(default=True)),
                ('requires_manager_review', models.BooleanField(default=True)),
                ('requires_peer_feedback', models.BooleanField(default=False)),
                ('max_peer_feedback', models.PositiveIntegerField(default=3)),
                ('goal_weight_percentage', models.PositiveIntegerField(default=70)),
                ('competency_weight_percentage', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cycle Template',
                'verbose_name_plural': 'Cycle Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the review cycle', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the review cycle')),
                ('cycle_type', models.CharField(choices=[('annual', 'Annual'), ('mid_year', 'Mid-Year'), ('quarterly', 'Quarterly'), ('probation', 'Probation'), ('project', 'Project-Based')], default='annual', help_text='Type of review cycle', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the cycle', max_length=20)),
                ('start_date', models.DateField(help_text='Start date of the review cycle')),
                ('end_date', models.DateField(help_text='End date of the review cycle')),
                ('goal_setting_start', models.DateField(help_text='Start date for goal setting period')),
                ('goal_setting_end', models.DateField(help_text='End date for goal setting period')),
                ('self_review_start', models.DateField(help_text='Start date for self-review period')),
                ('self_review_end', models.DateField(help_text='End date for self-review period')),
                ('manager_review_start', models.DateField(help_text='Start date for manager review period')),
                ('manager_review_end', models.DateField(help_text='End date for manager review period')),
                ('calibration_start', models.DateField(blank=True, help_text='Start date for calibration period', null=True)),
                ('calibration_end', models.DateField(blank=True, help_text='End date for calibration period', null=True)),
                ('requires_goals', models.BooleanField(default=True, help_text='Whether this cycle requires goal setting')),
                ('requires_self_review', models.BooleanField(default=True, help_text='Whether this cycle requires self-review')),
                ('requires_manager_review', models.BooleanField(default=True, help_text='Whether this cycle requires manager review')),
                ('requires_peer_feedback', models.BooleanField(default=False, help_text='Whether this cycle requires peer feedback')),
                ('max_peer_feedback', models.PositiveIntegerField(default=3, help_text='Maximum number of peer feedback requests per employee', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('goal_weight_percentage', models.PositiveIntegerField(default=70, help_text='Percentage weight of goals in overall evaluation', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('competency_weight_percentage', models.PositiveIntegerField(default=30, help_text='Percentage weight of competencies in overall evaluation', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the cycle is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this cycle', on_delete=django.db.models.deletion.CASCADE, related_name='created_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Cycle',
                'verbose_name_plural': 'Review Cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CycleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the employee is actively participating')),
                ('goals_set', models.BooleanField(default=False, help_text='Whether the employee has set their goals')),
                ('goals_approved', models.BooleanField(default=False, help_text="Whether the employee's goals have been approved")),
                ('self_review_completed', models.BooleanField(default=False, help_text='Whether the self-review is completed')),
                ('manager_review_completed', models.BooleanField(default=False, help_text='Whether the manager review is completed')),
                ('peer_feedback_requested', models.BooleanField(default=False, help_text='Whether peer feedback has been requested')),
                ('peer_feedback_completed', models.BooleanField(default=False, help_text='Whether peer feedback is completed')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the cycle was completed for this employee', null=True)),
                ('notes', models.TextField(blank=True, help_text="Notes about this participant's cycle")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee participating in the cycle', on_delete=django.db.models.deletion.CASCADE, related_name='cycle_participations', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, help_text='Manager for this employee in this cycle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cycles', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(help_text='Review cycle', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='cycles.reviewcycle')),
            ],
            options={
                'verbose_name': 'Cycle Participant',
                'verbose_name_plural': 'Cycle Participants',
                'ordering': ['employee__employee_id'],
                'unique_together': {('cycle', 'employee')},
            },
        ),
    ]
