# Generated by Django 5.0.1 on 2025-10-13 20:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Competency name', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the competency')),
                ('category', models.CharField(choices=[('leadership', 'Leadership'), ('technical', 'Technical'), ('communication', 'Communication'), ('teamwork', 'Teamwork'), ('problem_solving', 'Problem Solving'), ('innovation', 'Innovation'), ('customer_focus', 'Customer Focus'), ('other', 'Other')], help_text='Competency category', max_length=50)),
                ('proficiency_levels', models.JSONField(help_text='Proficiency levels and descriptions')),
                ('behavioral_indicators', models.JSONField(help_text='Observable behaviors for each proficiency level')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this competency is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Competency',
                'verbose_name_plural': 'Competencies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RatingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rating scale name', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Description of the rating scale')),
                ('scale_type', models.CharField(choices=[('numeric', 'Numeric (e.g., 1-5)'), ('descriptive', 'Descriptive (e.g., Exceeds/Meets/Below)'), ('percentage', 'Percentage (0-100%)')], default='numeric', help_text='Type of rating scale', max_length=20)),
                ('min_value', models.IntegerField(default=1, help_text='Minimum rating value')),
                ('max_value', models.IntegerField(default=5, help_text='Maximum rating value')),
                ('scale_points', models.JSONField(help_text='Scale points with labels and descriptions')),
                ('usage_guidance', models.TextField(blank=True, help_text='Guidance text for managers using this scale')),
                ('distribution_guidelines', models.JSONField(blank=True, help_text='Expected distribution of ratings (e.g., {5: 10%, 4: 20%, 3: 40%, 2: 20%, 1: 10%})', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this scale is available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rating Scale',
                'verbose_name_plural': 'Rating Scales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CycleRatingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False, help_text='Whether the rating scale is locked (set when cycle becomes active)')),
                ('locked_at', models.DateTimeField(blank=True, help_text='When the rating scale was locked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.OneToOneField(help_text='Review cycle', on_delete=django.db.models.deletion.CASCADE, related_name='rating_scale_config', to='cycles.reviewcycle')),
                ('rating_scale', models.ForeignKey(help_text='Selected rating scale', on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='cycles.ratingscale')),
            ],
            options={
                'verbose_name': 'Cycle Rating Scale',
                'verbose_name_plural': 'Cycle Rating Scales',
            },
        ),
        migrations.AddField(
            model_name='cycletemplate',
            name='default_rating_scale',
            field=models.ForeignKey(blank=True, help_text='Default rating scale for cycles created from this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_defaults', to='cycles.ratingscale'),
        ),
        migrations.CreateModel(
            name='TemplateCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=10, help_text='Default weight for this competency', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('competency', models.ForeignKey(help_text='Competency', on_delete=django.db.models.deletion.CASCADE, to='cycles.competency')),
                ('template', models.ForeignKey(help_text='Cycle template', on_delete=django.db.models.deletion.CASCADE, to='cycles.cycletemplate')),
            ],
            options={
                'verbose_name': 'Template Competency',
                'verbose_name_plural': 'Template Competencies',
                'unique_together': {('template', 'competency')},
            },
        ),
        migrations.AddField(
            model_name='cycletemplate',
            name='template_competencies',
            field=models.ManyToManyField(help_text='Default competencies for this template', related_name='templates', through='cycles.TemplateCompetency', to='cycles.competency'),
        ),
        migrations.CreateModel(
            name='CycleCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(help_text='Weight of this competency in overall evaluation (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_required', models.BooleanField(default=True, help_text='Whether evaluation of this competency is required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competency', models.ForeignKey(help_text='Competency being evaluated', on_delete=django.db.models.deletion.CASCADE, related_name='cycle_assignments', to='cycles.competency')),
                ('cycle', models.ForeignKey(help_text='Review cycle', on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='cycles.reviewcycle')),
            ],
            options={
                'verbose_name': 'Cycle Competency',
                'verbose_name_plural': 'Cycle Competencies',
                'ordering': ['-weight', 'competency__name'],
                'unique_together': {('cycle', 'competency')},
            },
        ),
    ]
