# Generated by Django 5.0.1 on 2025-10-18 08:22

from django.db import migrations
import time


def fix_duplicate_employee_ids(apps, schema_editor):
    """Fix any duplicate employee IDs in the database."""
    User = apps.get_model('accounts', 'User')
    
    # Find users with duplicate employee IDs
    from django.db.models import Count
    duplicates = User.objects.values('employee_id').annotate(
        count=Count('employee_id')
    ).filter(count__gt=1)
    
    for duplicate in duplicates:
        employee_id = duplicate['employee_id']
        users = User.objects.filter(employee_id=employee_id).order_by('id')
        
        # Keep the first user, update the rest
        for i, user in enumerate(users[1:], 1):
            # Generate a new unique employee ID
            timestamp = int(time.time() * 1000) % 1000000
            new_employee_id = f"EMP{timestamp + i:06d}"
            
            # Ensure the new ID is unique
            while User.objects.filter(employee_id=new_employee_id).exists():
                timestamp += 1
                new_employee_id = f"EMP{timestamp:06d}"
            
            user.employee_id = new_employee_id
            user.save()


def reverse_fix_duplicate_employee_ids(apps, schema_editor):
    """Reverse migration - no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(
            fix_duplicate_employee_ids,
            reverse_fix_duplicate_employee_ids
        ),
    ]
