# Generated by Django 5.0.1 on 2025-10-13 13:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('review_type', models.CharField(choices=[('self', 'Self Review'), ('manager', 'Manager Review'), ('peer', 'Peer Review'), ('360', '360 Review')], help_text='Type of review this template is for', max_length=20)),
                ('sections', models.JSONField(help_text='List of sections in the template')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the template is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review Template',
                'verbose_name_plural': 'Review Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('self', 'Self Review'), ('manager', 'Manager Review'), ('peer', 'Peer Review'), ('360', '360 Review')], help_text='Type of review', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('completed', 'Completed')], default='draft', help_text='Current status of the review', max_length=20)),
                ('overall_rating', models.PositiveIntegerField(blank=True, help_text='Overall performance rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('achievements', models.TextField(blank=True, help_text='Key achievements and accomplishments')),
                ('challenges', models.TextField(blank=True, help_text='Challenges faced and how they were addressed')),
                ('development_areas', models.TextField(blank=True, help_text='Areas for development and improvement')),
                ('goals_for_next_period', models.TextField(blank=True, help_text='Goals for the next review period')),
                ('comments', models.TextField(blank=True, help_text='Additional comments and observations')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the review was submitted', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the review was approved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(help_text='Review cycle this review belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cycles.reviewcycle')),
                ('employee', models.ForeignKey(help_text='Employee being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(help_text='Person conducting the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'reviewer', 'cycle', 'review_type')},
            },
        ),
        migrations.CreateModel(
            name='ReviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Section description')),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Rating for this section (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, help_text='Comments for this section')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this section in the review')),
                ('review', models.ForeignKey(help_text='Review this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reviews.review')),
            ],
            options={
                'verbose_name': 'Review Section',
                'verbose_name_plural': 'Review Sections',
                'ordering': ['order', 'title'],
            },
        ),
    ]
