# Generated by Django 5.0.1 on 2025-10-13 21:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_competency_ratingscale_cycleratingscale_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('completed', 'Completed')], default='not_started', help_text='Current status of self-review', max_length=20)),
                ('goal_achievements', models.JSONField(default=dict, help_text='Goal achievement analysis per approved goal. Format: {goal_id: {text, word_count, evidence_links}}')),
                ('key_accomplishments', models.TextField(blank=True, help_text='Notable achievements and impact during review period (200-800 words)')),
                ('key_accomplishments_word_count', models.PositiveIntegerField(default=0, help_text='Word count for key accomplishments')),
                ('recognition_received', models.TextField(blank=True, help_text='Awards, feedback, or acknowledgments received')),
                ('competency_assessments', models.JSONField(default=dict, help_text='Self-assessment for each competency. Format: {competency_id: {rating, text, word_count, examples}}')),
                ('development_areas', models.TextField(blank=True, help_text='Growth opportunities and areas for improvement (200-600 words)')),
                ('development_areas_word_count', models.PositiveIntegerField(default=0, help_text='Word count for development areas')),
                ('learning_initiatives', models.TextField(blank=True, help_text='Training, courses, or development activities completed')),
                ('skill_gaps', models.TextField(blank=True, help_text='Honest assessment of skills needing development')),
                ('career_aspirations', models.TextField(blank=True, help_text='Professional objectives for next 1-3 years (150-400 words)')),
                ('career_aspirations_word_count', models.PositiveIntegerField(default=0, help_text='Word count for career aspirations')),
                ('role_interests', models.TextField(blank=True, help_text='Desired career progression or lateral moves')),
                ('skill_development_goals', models.TextField(blank=True, help_text='Capabilities employee wants to build')),
                ('goal_references', models.JSONField(default=list, help_text='List of goal IDs referenced in self-review')),
                ('feedback_references', models.JSONField(default=list, help_text='List of peer feedback IDs referenced')),
                ('document_attachments', models.JSONField(default=list, help_text='List of attached documents with URLs')),
                ('last_auto_save', models.DateTimeField(blank=True, help_text='Timestamp of last auto-save', null=True)),
                ('auto_save_count', models.PositiveIntegerField(default=0, help_text='Number of auto-saves performed')),
                ('last_manual_save', models.DateTimeField(blank=True, help_text='Timestamp of last manual save', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When self-review was submitted (BR-030)', null=True)),
                ('submission_version', models.PositiveIntegerField(default=1, help_text='Version number at submission')),
                ('submission_hash', models.CharField(blank=True, help_text='Hash of submitted content for integrity verification', max_length=64)),
                ('is_locked', models.BooleanField(default=False, help_text='Whether self-review is locked after submission (BR-030)')),
                ('section_completion', models.JSONField(default=dict, help_text='Completion status for each section')),
                ('overall_completion_percentage', models.PositiveIntegerField(default=0, help_text='Overall completion percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(help_text='Review cycle this self-review belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='self_reviews', to='cycles.reviewcycle')),
                ('employee', models.ForeignKey(help_text='Employee completing self-review', on_delete=django.db.models.deletion.CASCADE, related_name='self_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='User who submitted (should match employee)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_self_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Self Review',
                'verbose_name_plural': 'Self Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='SelfReviewAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_url', models.URLField(help_text='URL to the file (S3, cloud storage, etc.)')),
                ('file_type', models.CharField(help_text='MIME type of the file', max_length=50)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('description', models.TextField(blank=True, help_text='Description of the attachment')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('self_review', models.ForeignKey(help_text='Self-review this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reviews.selfreview')),
            ],
            options={
                'verbose_name': 'Self Review Attachment',
                'verbose_name_plural': 'Self Review Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SelfReviewVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Version number')),
                ('content_snapshot', models.JSONField(help_text='Complete snapshot of self-review content')),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('auto_saved', 'Auto Saved'), ('manually_saved', 'Manually Saved'), ('submitted', 'Submitted'), ('reopened', 'Reopened')], help_text='Type of change', max_length=20)),
                ('change_summary', models.TextField(blank=True, help_text='Summary of changes made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_review_versions', to=settings.AUTH_USER_MODEL)),
                ('self_review', models.ForeignKey(help_text='Self-review this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='reviews.selfreview')),
            ],
            options={
                'verbose_name': 'Self Review Version',
                'verbose_name_plural': 'Self Review Versions',
                'ordering': ['-version_number', '-created_at'],
                'unique_together': {('self_review', 'version_number')},
            },
        ),
    ]
