# Generated by Django 5.0.1 on 2025-10-18 07:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_competency_ratingscale_cycleratingscale_and_more'),
        ('reviews', '0002_selfreview_selfreviewattachment_selfreviewversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('goal', 'Goal Reference'), ('feedback', 'Peer Feedback'), ('document', 'Document Attachment'), ('url', 'URL Link'), ('metric', 'Performance Metric')], help_text='Type of evidence link', max_length=20)),
                ('title', models.CharField(help_text='Title or description of the evidence', max_length=200)),
                ('reference_id', models.IntegerField(blank=True, help_text='ID of referenced goal or feedback', null=True)),
                ('url', models.URLField(blank=True, help_text='URL link if applicable')),
                ('file_attachment', models.FileField(blank=True, help_text='File attachment if applicable', null=True, upload_to='self_review_evidence/')),
                ('description', models.TextField(blank=True, help_text='Additional description of the evidence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evidence Link',
                'verbose_name_plural': 'Evidence Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period_start', models.DateField(help_text='Start date of the review period')),
                ('review_period_end', models.DateField(help_text='End date of the review period')),
                ('goals_achievements', models.TextField(blank=True, help_text="Manager's assessment of goal achievements")),
                ('communication_rating', models.IntegerField(blank=True, help_text='Communication skills rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('collaboration_rating', models.IntegerField(blank=True, help_text='Collaboration skills rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('leadership_rating', models.IntegerField(blank=True, help_text='Leadership skills rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('problem_solving_rating', models.IntegerField(blank=True, help_text='Problem-solving skills rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('adaptability_rating', models.IntegerField(blank=True, help_text='Adaptability rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_rating', models.IntegerField(blank=True, help_text='Overall performance rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('performance_summary', models.TextField(blank=True, help_text="Manager's performance summary narrative")),
                ('strengths', models.TextField(blank=True, help_text="Employee's key strengths")),
                ('development_areas', models.TextField(blank=True, help_text='Areas for development and improvement')),
                ('career_recommendations', models.TextField(blank=True, help_text='Career development recommendations')),
                ('comments', models.TextField(blank=True, help_text='Additional comments (max 5000 characters)')),
                ('private_notes', models.TextField(blank=True, help_text='Private manager notes (not visible to employee)')),
                ('development_notes', models.TextField(blank=True, help_text='Development planning notes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('returned', 'Returned for Revision')], default='draft', help_text='Current status of the review', max_length=20)),
                ('is_locked', models.BooleanField(default=False, help_text='Whether the review is locked from editing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('last_auto_save', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(help_text='Performance cycle for this review', on_delete=django.db.models.deletion.CASCADE, related_name='manager_reviews', to='cycles.reviewcycle')),
                ('employee', models.ForeignKey(help_text='Employee being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='manager_reviews_received', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(help_text='Manager conducting the review', on_delete=django.db.models.deletion.CASCADE, related_name='manager_reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manager Review',
                'verbose_name_plural': 'Manager Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'cycle', 'manager')},
            },
        ),
        migrations.CreateModel(
            name='ReviewAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded file', upload_to='review_attachments/')),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('spreadsheet', 'Spreadsheet'), ('presentation', 'Presentation'), ('other', 'Other')], help_text='Type of attachment', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of the attachment')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('manager_review', models.ForeignKey(help_text='The manager review this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reviews.managerreview')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Attachment',
                'verbose_name_plural': 'Review Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('returned', 'Returned'), ('locked', 'Locked'), ('unlocked', 'Unlocked')], help_text='Type of action performed', max_length=20)),
                ('field_changed', models.CharField(blank=True, help_text='Field that was changed', max_length=50)),
                ('old_value', models.TextField(blank=True, help_text='Previous value')),
                ('new_value', models.TextField(blank=True, help_text='New value')),
                ('change_summary', models.TextField(blank=True, help_text='Summary of changes made')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('manager_review', models.ForeignKey(help_text='The manager review this audit entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='reviews.managerreview')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Audit Trail',
                'verbose_name_plural': 'Review Audit Trails',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SelfReviewAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('auto_saved', 'Auto-saved'), ('submitted', 'Submitted'), ('returned', 'Returned'), ('completed', 'Completed')], help_text='Type of action performed', max_length=20)),
                ('section_type', models.CharField(blank=True, help_text='Section that was modified', max_length=20)),
                ('changes_summary', models.TextField(blank=True, help_text='Summary of changes made')),
                ('previous_content', models.TextField(blank=True, help_text='Previous content before change')),
                ('new_content', models.TextField(blank=True, help_text='New content after change')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
            ],
            options={
                'verbose_name': 'Self Review Audit Trail',
                'verbose_name_plural': 'Self Review Audit Trails',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SelfReviewDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(help_text='Type of section being drafted', max_length=20)),
                ('content', models.TextField(help_text='Draft content')),
                ('word_count', models.IntegerField(default=0, help_text='Word count of draft content')),
                ('is_auto_save', models.BooleanField(default=True, help_text='Whether this is an automatic save')),
                ('save_reason', models.CharField(default='auto_save', help_text='Reason for saving (auto_save, manual_save, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Self Review Draft',
                'verbose_name_plural': 'Self Review Drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelfReviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('goal_achievement', 'Goal Achievement Summary'), ('accomplishments', 'Key Accomplishments'), ('competencies', 'Behavioral Competencies'), ('development', 'Development Areas'), ('career', 'Career Aspirations')], help_text='Type of section', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Section content')),
                ('word_count', models.IntegerField(default=0, help_text='Current word count')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether section is marked as completed')),
                ('min_words', models.IntegerField(default=0, help_text='Minimum word count required')),
                ('max_words', models.IntegerField(default=1000, help_text='Maximum word count allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Self Review Section',
                'verbose_name_plural': 'Self Review Sections',
                'ordering': ['section_type'],
            },
        ),
        migrations.CreateModel(
            name='SelfReviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('sections_config', models.JSONField(default=dict, help_text='Configuration for each section including word limits')),
                ('writing_guidelines', models.TextField(blank=True, help_text='Writing guidelines and tips')),
                ('examples', models.JSONField(default=list, help_text='Example responses for each section')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_review_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Self Review Template',
                'verbose_name_plural': 'Self Review Templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='review',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='review',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='reviewsection',
            name='review',
        ),
        migrations.DeleteModel(
            name='ReviewTemplate',
        ),
        migrations.RemoveField(
            model_name='selfreviewattachment',
            name='self_review',
        ),
        migrations.AlterUniqueTogether(
            name='selfreviewversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='selfreviewversion',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='selfreviewversion',
            name='self_review',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='auto_save_count',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='career_aspirations_word_count',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='competency_assessments',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='development_areas_word_count',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='document_attachments',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='feedback_references',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='goal_achievements',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='goal_references',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='key_accomplishments_word_count',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='last_manual_save',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='learning_initiatives',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='overall_completion_percentage',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='recognition_received',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='role_interests',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='section_completion',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='skill_development_goals',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='skill_gaps',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='submission_hash',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='submission_version',
        ),
        migrations.RemoveField(
            model_name='selfreview',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='selfreview',
            name='behavioral_competencies',
            field=models.TextField(blank=True, help_text='Self-assessment of behavioral competencies'),
        ),
        migrations.AddField(
            model_name='selfreview',
            name='completion_percentage',
            field=models.IntegerField(default=0, help_text='Percentage of review completion', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='selfreview',
            name='goal_achievement_summary',
            field=models.TextField(blank=True, help_text='Summary of goal achievements with evidence'),
        ),
        migrations.AddField(
            model_name='selfreview',
            name='goals_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selfreview',
            name='peer_feedback_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selfreview',
            name='prerequisites_met',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='selfreview',
            name='career_aspirations',
            field=models.TextField(blank=True, help_text='Future goals and career objectives'),
        ),
        migrations.AlterField(
            model_name='selfreview',
            name='cycle',
            field=models.ForeignKey(help_text='Performance cycle for this review', on_delete=django.db.models.deletion.CASCADE, related_name='self_reviews', to='cycles.reviewcycle'),
        ),
        migrations.AlterField(
            model_name='selfreview',
            name='development_areas',
            field=models.TextField(blank=True, help_text='Areas for growth and development'),
        ),
        migrations.AlterField(
            model_name='selfreview',
            name='employee',
            field=models.ForeignKey(help_text='Employee completing the self-review', on_delete=django.db.models.deletion.CASCADE, related_name='self_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='selfreview',
            name='key_accomplishments',
            field=models.TextField(blank=True, help_text='Notable achievements and contributions'),
        ),
        migrations.AlterField(
            model_name='selfreview',
            name='last_auto_save',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selfreview',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('returned', 'Returned for Revision')], default='draft', help_text='Current status of the self-review', max_length=20),
        ),
        migrations.AlterField(
            model_name='selfreview',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencelink',
            name='self_review',
            field=models.ForeignKey(help_text='The self-review this evidence belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='reviews.selfreview'),
        ),
        migrations.AddField(
            model_name='selfreviewaudittrail',
            name='self_review',
            field=models.ForeignKey(help_text='The self-review this audit entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='reviews.selfreview'),
        ),
        migrations.AddField(
            model_name='selfreviewaudittrail',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_review_audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selfreviewdraft',
            name='self_review',
            field=models.ForeignKey(help_text='The self-review this draft belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='reviews.selfreview'),
        ),
        migrations.AddField(
            model_name='selfreviewsection',
            name='self_review',
            field=models.ForeignKey(help_text='The self-review this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reviews.selfreview'),
        ),
        migrations.AddField(
            model_name='evidencelink',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Specific section this evidence relates to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='reviews.selfreviewsection'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ReviewSection',
        ),
        migrations.DeleteModel(
            name='SelfReviewAttachment',
        ),
        migrations.DeleteModel(
            name='SelfReviewVersion',
        ),
        migrations.AlterUniqueTogether(
            name='selfreviewsection',
            unique_together={('self_review', 'section_type')},
        ),
    ]
